### ISSUE TITLE
Errors with grep, column on initial run

### ISSUE THREAD

**Issue by doctorfree** [flexibeast/kitty_keys#1]
Thank you for the useful script. In my initial runs on Ubuntu Linux 20.04 and macOS Monterey 12.6.2 the `kitty_keys` function works and displays my Kitty key bindings but I get some error output from `grep` and `column`.

On my Linux system the error is:
```
grep: Unmatched [, [^, [:, [., or [=
```

On macOS the error is:
```
grep: brackets ([ ]) not balanced
column: line too long
(null)
```

I can get rid of this error output from grep and column by redirecting stderr to /dev/null in the script.

Perhaps these errors are indicative of some improper key bindings in my setup or too many or some other issue in my Kitty config. I have not tracked down the source of these.

Here is the output of `diff -Naur ...` showing my simple changes (not really sure whether hiding these errors is a good idea):

```
--- kitty_keys.sh.00	2023-02-19 12:14:08.000000000 -0800
+++ kitty_keys.sh	2023-02-19 12:14:37.000000000 -0800
@@ -141,7 +141,7 @@
         IFS=' '
         for B in $BINDINGS
         do
-            if print1 "${DEFAULTS}" | grep -q "${B}"
+            if print1 "${DEFAULTS}" | grep -q "${B}" 2> /dev/null
             then
                 DEFAULTS=$(print1 "${DEFAULTS}" | sed "/${B}/d")
             fi
@@ -213,14 +213,14 @@
             ;;
     esac
 
-    print1 "${LEADING}${OUT}" | column -t -s':'
+    print1 "${LEADING}${OUT}" | column -t -s':' 2> /dev/null
     if [ -n "${WANT_FOOTER}" -a -n "${FOOTER}" ]
     then
         print1 "${FOOTER}\n"
     fi
     if [ -n "${TRAILING}" ]
     then
-        print1 "${TRAILING}" | column -t -s':'
+        print1 "${TRAILING}" | column -t -s':' 2> /dev/null
     fi
 
     # Remove convenience function from environment.
```

**Comment by flexibeast** [comment]
Thanks for the report! Yeah, let's not suppress the error messages; hopefully they should point the way to fixing this. :-)

1. Regarding the unmatched delimiter issue, my suggestion would be to remove the `-q` flag from the script's call to `grep`, so that you can see which of your bindings is resulting in that error message.

2. Are you setting the value of `KITTY_KEYS_TRAILING` to something other than the default? If so, to what? If not, i don't understand why `column` would be producing that error, since all it's being passed is `":\n"`.

**Comment by doctorfree** [comment]
Thanks for the prompt response. Removing the `-q` did not provide any additional info and I do not have a custom `KITTY_KEYS_TRAILING`. I was able to find the unmatched `[` culprit in my Kitty config:

```
map shift+cmd+[         previous_tab
```

If I comment that line out of `kitty.conf` then the `grep` error disappears.

So, Kitty key maps with some characters like `[` might not pass thru `grep` without error.

I've not tracked down the issue with `column`. That only occurs on my Mac so it may be that I need the `column` from `util-linux` on my Mac for that to work.

**Comment by flexibeast** [comment]
Thanks for tracking that down. The `printf(1)` provided as part of GNU Coreutils has a `%q` format sequence to escape various characters, but unfortunately, that's not required by POSIX. i'll try to find some other POSIX-compatible approach; in the end i might just need to do such escaping manually.

i'd prefer that non-Linux users have to use a particular `column(1)` implementation, so am interested in the `column(1)` implementation used on macOS. i presume it's likely to be a BSD implementation; does its man page give any information in this regard?

**Comment by flexibeast** [comment]
Actually, quick thought: Does using `-qF` instead of just `-q` with that grep call fix the problem?

**Comment by doctorfree** [comment]
Yes, `column` on macOS is almost surely the BSD implementation. The man page for column on my mac includes:

```
HISTORY
     The column command appeared in 4.3BSD-Reno.
```

Using `-qF` avoids the grep error message on both my Linux and Mac systems. Thanks!

**Comment by flexibeast** [comment]
Thanks - i've just pushed an update to use `-F` in the call to grep.

Yeah, that's the HISTORY section i have on my own (Gentoo) system, from which i derived the note in the README about `column(1)`, and which is provided by `util-linux` .... Is column(1) on your Mac available *without* having installed `util-linux`? Either way, what's the reported size of the binary? i'm trying to work out if there's some difference in the binaries, even if the man pages are the same, or if there's some other factor that's causing the problem with `column` on your Mac.

**Comment by doctorfree** [comment]
I didn't have `util-linux` installed on my Mac. That was `/usr/bin/column` and its man page which I believe is of BSD heritage. I installed `util-linux` with Homebrew and here are the sizes for both column binaries.

The Mac column binary in /usr/bin:
```
ls -l /usr/bin/column
-rwxr-xr-x  1 root  wheel  167952 Dec  2 00:43 /usr/bin/column
```
The Homebrew binary in the util-linux package:
```
ls -l /usr/local/Cellar/util-linux/2.38.1/bin/column
-r-xr-xr-x  1 doctorwhen  wheel  77112 Feb 23 07:07 /usr/local/Cellar/util-linux/2.38.1/bin/column
```

If I replace `column` in the kitty_keys script with `/usr/local/Cellar/util-linux/2.38.1/bin/column` and re-source it then everything works. I don't know how to make the BSD column provide the same functionality as the util-linux column but I will try when I have time. The BSD binary doesn't have a help option, just the man page. The man page indicates all it supports are the following:

```
SYNOPSIS
     column [-tx] [-c columns] [-s sep] [file ...]

DESCRIPTION
     The column utility formats its input into multiple columns.  Rows are filled
     before columns.  Input is taken from file operands, or, by default, from the
     standard input.  Empty lines are ignored.

     The options are as follows:

     -c      Output is formatted for a display columns wide.

     -s      Specify a set of characters to be used to delimit columns for the -t
             option.

     -t      Determine the number of columns the input contains and create a
             table.  Columns are delimited with whitespace, by default, or with
             the characters supplied using the -s option.  Useful for pretty-
             printing displays.

     -x      Fill columns before filling rows.
```

**Comment by flexibeast** [comment]
Thanks. So they're definitely different binaries.

It's weird, because the function's use of `column` only makes use of the `-t` and `-s` options, both of which are supported according to the man page output you posted:

    -s      Specify a set of characters to be used to delimit columns for the -t
            option.

    -t      Determine the number of columns the input contains and create a
            table.  Columns are delimited with whitespace, by default, or with
            the characters supplied using the -s option.  Useful for pretty-
            printing displays.

 Here's the equivalent section of the man page for the util-linux version:

    -s, --separator separators
        Specify the possible input item delimiters (default is whitespace).

    -t, --table
        Determine the number of columns the input contains and create a
        table. Columns are delimited with whitespace, by default, or with
        the characters supplied using the --output-separator option. Table
        output is useful for pretty-printing.

Reading both, i'm wondering whether the `-s` option to the Mac version isn't an input delimiter, but an output delimiter, i.e. Mac `column`'s `-s` is actually equivalent to util-linux `column`'s `--output-separator`?

If you can point me to the source for the Mac version, i'm happy to compile it myself and experiment with it. Otherwise, yeah, let me know the results of your own research. :-)

**Comment by flexibeast** [comment]
Actually, i've decided to just do an end-run around the whole issue, and instead use awk to achieve the same effect .... Can you please test the changes and confirm that they work on both your systems?

**Comment by doctorfree** [comment]
Moving from column to awk is a good idea. The current script using `awk` and `grep -qF` works for me on both macOS and Ubuntu 20.04. I am closing this issue. Thanks!
